services:
  reverse-proxy:
    image: traefik:v3.3
    command: --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/acme.json:/acme.json
    networks:
      - traefik

  with-docker-multi-env-production:
    container_name: "90180"
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: with-docker-multi-env-production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.90180.rule=Host(`liam.ddns.net`)"
      - "traefik.http.routers.90180.entrypoints=websecure"
      - "traefik.http.routers.90180.tls=true"
      - "traefik.http.routers.90180.tls.certresolver=myresolver"
    networks:
      - traefik

networks:
  traefik:
    external: true
